name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-app:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o ./bin/sadwave-events-tg ./cmd/main.go
    - name: Test
      run: go test -v ./...
    - name: Generate config
      env:
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        SADWAVE_API_URL: ${{ secrets.SADWAVE_API_URL }}
      run: |
        eval "echo \"$(< config.json.dist)\"" > config.json
        cat config.json
        ls
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push image
      run: |
          docker build -t ${{ secrets.AZURE_PUBLISH_PROFILE }}/sadwave-events-tg .
          docker push ${{ secrets.AZURE_PUBLISH_PROFILE }}/sadwave-events-tg:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-app
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'SadWaveEventsTg'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        images: 'index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/sadwave-events-tg:latest'