name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: GOARCH=amd64 GOOS=linux go build -o ./bin/sadwave-events-tg ./cmd/main.go
    - name: Test
      run: go test -v ./...
    - name: Generate config
      env:
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        SADWAVE_API_URL: ${{ secrets.SADWAVE_API_URL }}
      run: eval "echo \"$(< ./config.json.dist)\"" > ./config.json
